package bt;

public abstract class FunctionBasedContract extends Contract {
    public long methodIdentifier; // TODO just store register, protected access so subclass can use

    /**
     * This method does not get compiled into contracts - its contents are generated by the compiler
     */
    @Override
    @Deprecated // To make sure people do not override
    public void txReceived() {
        methodIdentifier = getMessage(getCurrentTx()).value[0]; // Could this be made more efficient?
        throw new UnsupportedOperationException();
    }

    public abstract void onNoFunctionCalled();
}
